// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxsmzmxwtpbtvbansgep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4c216bXh3dHBidHZiYW5zZ2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MjgyMjAsImV4cCI6MjA1ODUwNDIyMH0.aLgtYCx0QIKqfXzg3ZjzunCn-taSs-irZHx-Eb6cFqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);